### ISSUE TITLE
Staged install error for R v3.6.1

### ISSUE THREAD

**Issue by tboonf** [vallenderlab/MicrobiomeR#101]
Hello, 
I have been trying to install the MicrobiomeR package in R 3.6.1 following the suggested method on https://microbiomer.vallenderlab.science/ but I have been receiving error messages and are not being able to install despite all dependencies have been fullfiled. 

I have also tried the following but it did not work: 
```console
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS = "true")
remotes::install_github("vallenderlab/MicrobiomeR")
```
Please help.
---

**Comment by sdhutchins** [comment]
Hi, @tboonf!

Could you post the error message from your R console here? We'll try to debug this as soon as we can.

**Comment by tboonf** [comment]
I have received these error messages have not been successful to install the package. I have also tried to use the latest version of remote for the installation:


ERROR: hard-coded installation path: please report to the package maintainer and use ‘--no-staged-install’
* removing ‘/home/nova/R/x86_64-pc-linux-gnu-library/3.6/MicrobiomeR’
Error: Failed to install 'MicrobiomeR' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpqxERa2/file6d1f1d88d0b3/MicrobiomeR_0.6.0.tar.gz’ had non-zero exit status

**Comment by sdhutchins** [comment]
Thanks for posting the full message, @tboonf.

I'm currently working on a fix.

**Comment by grabear** [comment]
Hi @tboonf!  @sdhutchins made a fix via #102 and #103.  Please try installing it again.

**Comment by sdhutchins** [comment]
hey @tboonf just wanted to check if you were able to get this working?

**Comment by tboonf** [comment]
Thanks for the great help. MicrobiomeR can now be installed on R v3.6.1.
