### ISSUE TITLE
Document the package in a separate file.

### ISSUE THREAD

**Issue by grabear** [vallenderlab/MicrobiomeR#12]
Use the [R Packages Book](http://r-pkgs.had.co.nz/man.html#man-packages) by Hadley to determine how to document an overview of the package.

The [MicrobiomeR Workflow and MicrobiomeR Formats documentation](83c66b18c9387497b54edd87f31eccf57ea514da) can be moved to this separate file.

**Comment by sdhutchins** [comment]
Addressed in #56 by @grabear
