### ISSUE TITLE
Update data files and rerun analysis.

### ISSUE THREAD

**Issue by grabear** [vallenderlab/MicrobiomeR#28]
- [x] The metadata file needs to be changed.  
    - [x] So does the RData files associated with it.  
- [x] Some of the documentation also needs to change to reflect the metadata file.
- [x] Also, data and extdata are 41 Mb total.  I will reduce the data file to only contain phyloseq objects and the metacoder objects in the phyloseq or raw format.  This should reduce the package size as well as build and install times.

**Comment by grabear** [comment]
Make sure to update your function documentation.

**Comment by grabear** [comment]
Add package data to the `object_handler` function as a valid object name inside the .RDA files.

**Comment by sdhutchins** [comment]
:eyes:

**Comment by sdhutchins** [comment]
This is ready to be closed imo. @grabear
