### ISSUE TITLE
Begin version bumps and NEWS.md.

### ISSUE THREAD

**Issue by grabear** [vallenderlab/MicrobiomeR#31]
Create a NEWS.md file for documenting changes, and bump the version of the package as we make PRs.

There is an article out there about how to version your packages, so I'll try to find that and link it here.

**Comment by sdhutchins** [comment]
I can work on this!

**Comment by sdhutchins** [comment]
I think pkgdown helps with this too.

**Comment by grabear** [comment]
Noice!  yea please do.  That would be dope.

And try to add some links to articles here as you go!  :sunglasses:

**Comment by grabear** [comment]
I think we've started doing this regularly now for each PR.
