### ISSUE TITLE
DESCRIPTION file Error for Phyloseq

### ISSUE THREAD

**Issue by grabear** [vallenderlab/MicrobiomeR#4]
I will try to reproduce this later, but I was having trouble building the package on my laptop.  My laptop didn't have phyloseq installed at the time, and I was unable to build the package.  I tried so many things in order to get it to install as a dependency of our package, but in the end I had to manually install it.

### TODO:

- Reproduce this bug.
- Find a way to fix this bug
    - Installation hooks?

**Comment by sdhutchins** [comment]
This has resolved itself.
