### ISSUE TITLE
Version and release schedule.

### ISSUE THREAD

**Issue by grabear** [vallenderlab/MicrobiomeR#45]
## Intro
Because we haven't been rolling out releases as we go, we need to come up with an arbitrary release number for the package for whenever we publish.  I'd like for it to be meaningful.

I think we should do a 1.0.0 whenever we push to master and continue with the MAJOR.MINOR.PATCH semantic versioning style.

As we patch, we've got to add the changes into the NEWS.md file.

## Resources
* Great Article:  https://semver.org/
* https://blog.codeship.com/best-practices-when-versioning-a-release/

**Comment by sdhutchins** [comment]
> ## Intro
> Because we haven't been rolling out releases as we go, we need to come up with an arbitrary release number for the package for whenever we publish. I'd like for it to be meaningful.
> 
> I think we should do a 1.0.0 whenever we push to master and continue with the MAJOR.MINOR.PATCH semantic versioning style.
> 
> As we patch, we've got to add the changes into the NEWS.md file.
> 
> ## Resources
> * Great Article:  https://semver.org/
> * https://blog.codeship.com/best-practices-when-versioning-a-release/

I like it.
