### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by sdhutchins** [vallenderlab/MicrobiomeR#47]
It would be great to have an identifiable logo for the package.

**Comment by grabear** [comment]
I have no idea what to do here right now...

**Comment by sdhutchins** [comment]
Haha

**Comment by sdhutchins** [comment]
> I have no idea what to do here right now...

Maybe this package can help

**Comment by sdhutchins** [comment]
Logo Example 1:

![microbiomer](https://user-images.githubusercontent.com/20976111/55105051-9fa32b80-5099-11e9-8288-18f7c308ff65.png)

**Comment by grabear** [comment]
@sdhutchins That looks awesome!
  
![](https://media1.giphy.com/media/YFFPjL7iCNNBppy49S/200w.gif?cid=5a38a5a25c9bab124f7542565575c0a3)

**Comment by sdhutchins** [comment]
# Logo Example 2:

![microbiomer](https://user-images.githubusercontent.com/20976111/55106545-3f15ed80-509d-11e9-8870-aa8e1d639a44.png)

**Comment by sdhutchins** [comment]
# Logo Example 3:

![microbiomer](https://user-images.githubusercontent.com/20976111/55106822-d9763100-509d-11e9-9370-2380f29d98f9.png)

**Comment by grabear** [comment]
@sdhutchins My favorite is example 2!

**Comment by sdhutchins** [comment]
# Logo Example 4:

![microbiomer](https://user-images.githubusercontent.com/20976111/55175099-aa6ac880-514c-11e9-82bb-a881d0504b94.png)

**Comment by sdhutchins** [comment]
# Logo Example 5:

![microbiomer](https://user-images.githubusercontent.com/20976111/55175920-34676100-514e-11e9-8cc6-3eedd0d06533.png)

**Comment by grabear** [comment]
Log#5 with light green text?
![image](https://user-images.githubusercontent.com/20953530/55176282-db4bfd00-514e-11e9-979c-2dde3c17838f.png)

**Comment by grabear** [comment]
Reverse that statement....

**Comment by grabear** [comment]
![image](https://user-images.githubusercontent.com/20953530/55176389-0cc4c880-514f-11e9-920c-f4fafb52b1bf.png)

**Comment by sdhutchins** [comment]
The colors are clashing a bit for me.

here's my code bythe way.

```r
library(hexsticker)

sticker("bacterie_ff.png", package="MicrobiomeR", p_size=20, p_color = "#ff8168", s_x=1, s_y=.75, s_width=.5, s_height=.5, h_fill = "#1B243C", h_color = "#ff8168", filename="microbiomer.png", url = "vallenderlab/MicrobiomeR", u_color = "#ff8168", dpi = 300, u_size = 4)

```
![bacterie_ff](https://user-images.githubusercontent.com/20976111/55176548-51506400-514f-11e9-9838-9795eea52be1.png)

**Comment by sdhutchins** [comment]
I like 1, 2, and 4 the most.

**Comment by grabear** [comment]
Nice!  I'll try it out.  Yea I agree.  I like the idea of having different colors between border and text.

From your posts I'm still a fanboy of 2.

**Comment by sdhutchins** [comment]
I was trying to use colors that were in our vallender lab logo...


![image](https://user-images.githubusercontent.com/20976111/55177174-99bc5180-5150-11e9-9d09-7e6a15fcc0ad.png)

**Comment by sdhutchins** [comment]
W

> Nice! I'll try it out. Yea I agree. I like the idea of having different colors between border and text.
> 
> From your posts I'm still a fanboy of 2.

Well, let's go with 2!

**Comment by grabear** [comment]
FWIW:
# No. 1
![microbiomer](https://user-images.githubusercontent.com/20953530/55177662-bb6a0880-5151-11e9-8bde-520152a592d9.png)

# No. 2 
![microbiomer](https://user-images.githubusercontent.com/20953530/55177734-e5bbc600-5151-11e9-9366-e109b3a0a82d.png)

**Comment by sdhutchins** [comment]
![microbiomer](https://user-images.githubusercontent.com/20976111/55179040-a93d9980-5154-11e9-8f85-5e70c4746433.png)

**Comment by grabear** [comment]
I like this one better than 2!

**Comment by sdhutchins** [comment]
Awesome, whenever the paper finishes being accepted, I can add the logo, doi, and citation information to the readme.
