### ISSUE TITLE
Update analysis and plot functions to account for more than 2 treatments.

### ISSUE THREAD

**Issue by grabear** [vallenderlab/MicrobiomeR#58]

**Comment by grabear** [comment]
# Heat Trees:
- [X] `MicrobiomeR::get_heat_tree_plots()` now works with data that contains more than one treatment group.  (See the _analysis vignette_ in the next PR).

# Correlation Plots:
- [ ] Get the `primary_data` and `secondary_data` variables using metacoder::heat_tree_matrix()` as a model.  
https://github.com/grunwaldlab/metacoder/blob/f4d4e41f95de85e4c0f2acc913cc64f6cc6a089d/R/heat_tree_matrix.R#L76-L108
- [ ] Add another for loop that will loop over these new datasets first, and return a list of plots.
- [ ] Remove the static treatment names.

**Comment by grabear** [comment]
Permalinks aren't working...

https://github.com/grunwaldlab/metacoder/blob/f4d4e41f95de85e4c0f2acc913cc64f6cc6a089d/R/heat_tree_matrix.R#L76-L108

**Comment by sdhutchins** [comment]
> Permalinks aren't working...
> 
> https://github.com/grunwaldlab/metacoder/blob/f4d4e41f95de85e4c0f2acc913cc64f6cc6a089d/R/heat_tree_matrix.R#L76-L108

Bizzare.... @github

**Comment by sdhutchins** [comment]
Once #72 is done, this should be ready to be closed.
