### ISSUE TITLE
Update function names.

### ISSUE THREAD

**Issue by grabear** [vallenderlab/MicrobiomeR#62]
- [x] `get_*()` is cringe worthy.
- [x] `create_*()` is _meh_, but more acceptable.
- [ ] Review other naming conventions.

**Comment by sdhutchins** [comment]
I think it comes down to a matter of how hard we're going to try on this lol

For sure, I think finding better or more descriptive verbs to help name functions is good. Ironically, I read about that this week (when I find the link I'll post it), but it was suggesting to keep function names shorter while naming them with verbs.

If you take a quick glance at the NAMESPACE files for metacoder and phyloseq...they also have some similar overused words like `calc`, `parse`, `get`. `vegan` on the other hand sticks with using a concept to define the function `betadisper` or `betadiver`. That may be worth investing. `create_pub_table` could become just `pub_table` or `df_to_table`.

Ultimately, I'm open to changing anything that'll make our functions easier to remember. Using a verb doesn't have to be what we do.

**Comment by sdhutchins** [comment]
Ready to be closed?
