### ISSUE TITLE
Prepare for first release and push to master.

### ISSUE THREAD

**Issue by grabear** [vallenderlab/MicrobiomeR#63]
We are getting super close!  So I wanted to start discussing our first release.

# Epic

This is an `Epic` issue.  Any other issues attached to this one are deemed necessary for the release.  Anything optional or something we _might_ want to fit in should not go here (even if we have the time to develop it).

**Comment by sdhutchins** [comment]
I think you've broken it down well. I'd add that what is in the `In Progress` column is enough for the first release outside of updating function names. 

Logo/Citations/Regenerating data can all be done after the 1st release.

**Comment by grabear** [comment]
Prepare the package for CRAN:

- https://cran.r-project.org/web/packages/policies.html#Submission
- https://jef.works/blog/2018/06/18/get-your-package-on-cran-in-10-steps/

**Comment by sdhutchins** [comment]
Awesomeness. I am working on the lab github site too.

**Comment by grabear** [comment]
Excellent!  I'm going to build a personal github site for myself, so I can figure out how jekyll works.  And then maybe I can help you with some of that.

At the very least I'll link my site from the lab's site.

**Comment by sdhutchins** [comment]
> Excellent! I'm going to build a personal github site for myself, so I can figure out how jekyll works. And then maybe I can help you with some of that.
> 
> At the very least I'll link my site from the lab's site.

YASSSS
