### ISSUE TITLE
CNAME file.

### ISSUE THREAD

**Issue by grabear** [vallenderlab/MicrobiomeR#80]
#76 #74

What's the deal with this?  Can it be moved to another folder or removed altogether?  It creates a note when using `devtools::check()`

**Comment by sdhutchins** [comment]
It needs to be in that folder. Is it causing a build issue?

**Comment by grabear** [comment]
Not an issue.  Just wondering, if it can be dealt with differently.  I'll add it to the .Rbuildignore file so that it doesn't create a `NOTE`.

**Comment by sdhutchins** [comment]
> Not an issue. Just wondering, if it can be dealt with differently. I'll add it to the .Rbuildignore file so that it doesn't create a `NOTE`.

Perfect.
